# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=128, unique=True)),
                ('appname', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('averscore', models.FloatField(default=0)),
                ('developer', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=128)),
                ('iconpath', models.CharField(max_length=128)),
                ('imagepath1', models.CharField(max_length=128)),
                ('imagepath2', models.CharField(max_length=128)),
                ('imagepath3', models.CharField(max_length=128)),
                ('viewcount', models.IntegerField(default=0)),
                ('likecount', models.IntegerField(default=0)),
                ('dislikecount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('app', models.ManyToManyField(to='AppRating.App')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppRating.Category'),
        ),
    ]
