# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='commentcount',
            field=models.IntegerField(default=0),
        ),
    ]
