# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppRating', '0002_app_commentcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='app',
        ),
        migrations.AddField(
            model_name='comment',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppRating.App'),
        ),
    ]
