# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRating', '0003_auto_20160320_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
